site_name: DocDam
docs_dir: 'md'
site_dir: 'docs'
theme:
  name: 'material'
  palette:
    primary: '#3f51b5'
    accent: '#e91e63'
    background: '#ffffff'
    surface: '#f5f5f5'
    error: '#f44336'
  custom_dir: 'docs/overrides'
nav:
  - Inici: index.md
  - EDD:
    - Act_1 : EDD/Tema_1/Act1.1.md
    - Act_2 : EDD/Tema_1/Act1.2.md
    - Act_3 : EDD/Tema_1/Act1.3.md
    - Act_4 : EDD/Tema_1/Act1.4.md
    - Article 5 : EDD/Tema_1/Act1.5.md
    - Article 6 : EDD/Tema_1/Act1.6.md
    - Article 7 : EDD/ControlDeVersions/git.md
    - Projecte1: EDD/ControlDeVersions/projecte1.md
    - Projecte2: EDD/ControlDeVersions/projecte2.md 
    - RC and subversion : 
      - Control de versiones y modelo iterativo :  EDD/RCAndSubversion/ControlDeVersionesYModeloIterativo.md
      - Desarrollo colaborativo : EDD/RCAndSubversion/DesarrolloColaborativo.md
      - Diferencias entre RCS y subversion : EDD/RCAndSubversion/DiferenciasEntreRCSYSubversion.md
    - Calculadora : EDD/calculadora/calculadora.md
    - Maven & Ant:
      - ANT : EDD/maven/ant.md
      - Act 1 : EDD/maven/maven1.md
      - Act 2 : EDD/maven/maven2.md
      - Act 3 : EDD/maven/maven3.md
  - LMI : 
    - JavaScript:
      - Act 1: LMI/JavaScript/1.js
      - Act 2: LMI/JavaScript/2.js
      - Act 3: LMI/JavaScript/3.js
      - Act 4: LMI/JavaScript/4.js
      - Act 5: LMI/JavaScript/5.js
      - Act 6: LMI/JavaScript/6.js
      - Act 7: LMI/JavaScript/7.js
      - Act 8: LMI/JavaScript/8.js
      - Act 9: LMI/JavaScript/9.js
      - Act 10: LMI/JavaScript/10.js
      - Act 11: LMI/JavaScript/11.js
      - Act 12: LMI/JavaScript/12.js
extra_css:
  - 'overrides/extra.css'