site_name: DocDam
theme:
  name: 'material'
  custom_dir: 'docs/overrides'
nav:
  - Inici: index.md
  - EDD:
    - Act_1 : EDD/Tema_1/Act1.1.md
    - Act_2 : EDD/Tema_1/Act1.2.md
    - Act_3 : EDD/Tema_1/Act1.3.md
    - Act_4 : EDD/Tema_1/Act1.4.md
    - Article 5 : EDD/Tema_1/Act1.5.md
    - Article 6 : EDD/Tema_1/Act1.6.md
    - Article 7 : EDD/ControlDeVersions/git.md
    - Projecte1: EDD/ControlDeVersions/projecte1.md
    - Projecte2: EDD/ControlDeVersions/projecte2.md 
    - RC and subversion : 
      - Control de versiones y modelo iterativo :  EDD/RCAndSubversion/ControlDeVersionesYModeloIterativo.md
      - Desarrollo colaborativo : EDD/RCAndSubversion/DesarrolloColaborativo.md
      - Diferencias entre RCS y subversion : EDD/RCAndSubversion/DiferenciasEntreRCSYSubversion.md
    - Calculadora : EDD/calculadora/calculadora.md
    - Maven:
      - Act 1 : EDD/maven/maven1.md
      - Act 2 : EDD/maven/maven2.md
      - Act 3 : EDD/maven/maven3.md
extra_css:
  - 'overrides/extra.css'